### PR TITLE
UI changes leveraging metadata

### PR DESCRIPTION
**Pull request by kouloumos**
This PR makes some UI changes that will leverage the added metadata. 
- (**1st commit**) Pages display title, speakers and date (if not a conference)
  regular

- (**2nd commit**) Taxonomy pages follow the same format as above, also displaying from where the transcript is
taxonomy

- (**3rd commit**) Count of transcripts for each taxonomy
  regular

- (**4th commit**) Support for transcripts that need review as a call to action for readers/contributors
sideit-image

- (**5th commit**) Display tags in each transcript's preview card
image

Live Demo:
- You can see the changes by visiting https://www.kouloumos.com/bitcointranscripts.github.io and using the sidebar to navigate to the transcripts.
- You can see the "Review needed" at the bottom of [this page](https://www.kouloumos.com/bitcointranscripts.github.io/chaincode-labs/chaincode-podcast/), and the AI-generated transcript [here](https://www.kouloumos.com/bitcointranscripts.github.io/chaincode-labs/chaincode-podcast/address-relay/)

_Note: the last commit is temporary, just to allow the build of the demo website on my own branch._

### CODE REVIEW

**Comment by adamjonas** [comment]
I appreciate the speakers page but I don't think that adding the dates is much of an upgrade across the board. Most conference pages will look similar to this:
Screen Shot 2022-11-14 at 8 30 35 PM

It makes more sense for a podcast or a meetup, but conferences happen within a day or two and mostly have subfolders, so the dates are of much use in an index view like this:
Screen Shot 2022-11-14 at 8 32 41 PM

So maybe you display by category?

**Comment by kouloumos** [comment]
> I appreciate the speakers page but I don't think that adding the dates is much of an upgrade across the board
> So maybe you display by category?

I get it, although I don't believe that this adds much noise. I've tried to conditionally display date if `tag != conference` but it has some issues with transcripts in the Misc category that also have this tag. The other solution is to add metadata on the conference page and display by that. This is much cleaner. I'll open a PR adding this field to all conferences (**edit**: did with [dc7a82f](https://github.com/bitcointranscripts/bitcointranscripts/commit/dc7a82f16ebbf7878b5be5552b843015dd676a2f)). 
```
---
title: TABConf
conference: True
---
```
Talking about conferences metadata, that's also a place that we could add their dates and some more info (videos?) if we wanted to.

I've also changed the way taxonomies are displayed (verifiable using the links in the PR description):

1. Count of transcripts for each taxonomy
Screenshot 2022-11-15 at 1 01 36 PM
 
3. Inside a speakers page more info are display for each transcript (in Hugo terminology, a specific speaker is a "term" in the "speakers" taxonomy)
Screenshot 2022-11-15 at 1 00 26 PM

**Comment by adamjonas** [comment]
Ready to revisit this now that the content updates are in. Thanks for your patience.

**Comment by kouloumos** [comment]
> Ready to revisit this now that the content updates are in. Thanks for your patience.

I was actually thinking to make a design brief and try to get some input from the Bitcoin Design community on the redesign.

**Comment by kouloumos** [comment]
> I was actually thinking to make a design brief and try to get some input from the Bitcoin Design community on the redesign.

My thought around the design brief was mostly to showcase the "needs ***{transcript, proof reading}***" functionality and get some input on how to display it. I never manage to do that, and as a redesign is not actually needed, I think that this can work as it is. Having the implementation there might make it easier to get design feedback in the future.

> Ready to revisit this now that the content updates are in. Thanks for your patience.

Ready to revisit. I also updated the PR description with an overview of the changes.

**Comment by kouloumos** [comment]
With the [new transcript queuing process](https://github.com/bitcointranscripts/transcription-review-backend/pull/245) nearing completion, I believe it's a good opportunity to revisit this PR. I've updated the PR description incorporating the latest changes.

Primarily, the 4th commit introduces changes aligned with the new queuing process. Additionally, I've utilized this opportunity to enhance the UI, aiming for improved discoverability and smoother navigation on the website.

Your input and review on these updates would be greatly appreciated. @adamjonas @aassoiants

**Pull request merged**
