### PR TITLE
update content 29-07-21

### PR DESCRIPTION
**Pull request by michaelfolkson**
Followed [these instructions](https://github.com/bitcointranscripts/bitcointranscripts/issues/42#issuecomment-887674468) to update the site with the latest transcript. I won't merge this so you can check this is ok before merging.

edit: I can't merge this even if I wanted to as I don't have merge access currently on this repo.

### CODE REVIEW

**Comment by adamjonas** [comment]
I sent an invite for write access when I added you as a member of the org. You should still be able to accept it.

**Comment by adamjonas** [comment]
That said, it doesn't appear that you pulled in the taproot rollout post. I did so in 7bc7018.

**Comment by michaelfolkson** [comment]
> I sent an invite for write access when I added you as a member of the org. You should still be able to accept it.

I found it, must have missed it at the time.... It has expired now though, I can't accept it.

> That said, it doesn't appear that you pulled in the taproot rollout post. I did so in 7bc7018.

Thanks for pulling it in. I'm not sure why it wasn't pulled in. I merged the PR in the other repo and then followed the instructions for updating the website. Any ideas what I did wrong?

**Comment by adamjonas** [comment]
You didn't pull down the content updates. I updated the instructions to hopefully adjust for it. You can try it next time.

You should have write permissions now.

**Pull request merged**
